import type { Metadata } from "next";
import { IBM_Plex_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/shared";
import ReactLenis from "lenis/react";

const ibmPlexMono = IBM_Plex_Mono({
  variable: "--font-ibm-plex-mono",
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  subsets: ["latin"],
  // variable: "--font-ibm-plex-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReactLenis
        root
        options={{
          smoothWheel: true,
          // wheelMultiplier: 0.5,
          infinite: false,
        }}
      >
        <body
          className={`antialiased ${ibmPlexMono} px-2 max-w-[1000px] mx-auto`}
        >
          <Header />
          {children}
        </body>
      </ReactLenis>
    </html>
  );
}
