import assets from "@/lib/assets";

export const collectionData = [
  {
    id: 1,
    name: "the colours",
    pcs: 10,
  },
  {
    id: 2,
    name: "the cracks",
    pcs: 10,
  },
  {
    id: 3,
    name: "faultlines",
    pcs: 10,
  },
  {
    id: 4,
    name: "fractal",
    pcs: 10,
  },
  {
    id: 5,
    name: "interstellar",
    pcs: 10,
  },
  {
    id: 6,
    name: "a collection of shadows",
    pcs: 10,
  },
  {
    id: 7,
    name: "m3t4m0rpho5is",
    pcs: 10,
  },
  {
    id: 8,
    name: "Chant",
    pcs: 10,
  },
  {
    id: 9,
    name: "Circles",
    pcs: 10,
  },
  {
    id: 10,
    name: "ethereal",
    pcs: 10,
  },
  {
    id: 11,
    name: "native soil",
    pcs: 10,
  },
  {
    id: 12,
    name: "Migration",
    pcs: 2,
  },
  {
    id: 13,
    name: "accessories",
    pcs: 10,
  },
];

export const collectionsData = [
  {
    id: 1,
    collection_name: "the colours",
    no_of_pieces: 19,
    pieces: [
      {
        id: 1,
        asset: assets.avocadoAndRage,
        piecename: "Avocado and Rage",
        sold_out: false,
        price: 72000,
      },
      {
        id: 2,
        asset: assets.balanceAndFreshness,
        piecename: "Balance and Freshness",
        sold_out: false,
        price: 72000,
      },
      {
        id: 3,
        asset: assets.chocolateAndSunshine,
        piecename: "Chocolate & Sunshine",
        sold_out: false,
        price: 72000,
      },
      {
        id: 4,
        asset: assets.creativityAndFushia,
        piecename: "Creativity & Fushia",
        sold_out: false,
        price: 72000,
      },
      {
        id: 5,
        asset: assets.earthAndPool,
        piecename: "Earth and Pool",
        sold_out: false,
        price: 72000,
      },
      {
        id: 6,
        asset: assets.fireAndRoyalty,
        piecename: "Fire & Royalty",
        sold_out: true,
        price: 72000,
      },
      {
        id: 7,
        asset: assets.goldAndCopper,
        piecename: "Gold and Copper",
        sold_out: false,
        price: 72000,
      },
      {
        id: 8,
        asset: assets.greyAndSong,
        piecename: "Grey and Song",
        sold_out: false,
        price: 72000,
      },
      {
        id: 9,
        asset: assets.guacamolaEgyptian,
        piecename: "Guacamola, Egyptian",
        sold_out: false,
        price: 72000,
      },
      {
        id: 10,
        asset: assets.lakeAndAlchemy,
        piecename: "Lake and Alchemy",
        sold_out: false,
        price: 72000,
      },
      {
        id: 11,
        asset: assets.limeAndObsidian,
        piecename: "Lime & Obsidian",
        sold_out: false,
        price: 72000,
      },
      {
        id: 12,
        asset: assets.mellowAndRomance,
        piecename: "Mellow and Romance",
        sold_out: false,
        price: 72000,
      },
      {
        id: 13,
        asset: assets.papayaAndNight,
        piecename: "Papaya and Night",
        sold_out: false,
        price: 72000,
      },
      {
        id: 14,
        asset: assets.patinaAndCalm,
        piecename: "Patina & Calm",
        sold_out: true,
        price: 72000,
      },
      {
        id: 15,
        asset: assets.roseAndMint,
        piecename: "Rose and Mint",
        sold_out: false,
        price: 72000,
      },
      {
        id: 16,
        asset: assets.skyAndMud,
        piecename: "Sky and Mud",
        sold_out: false,
        price: 72000,
      },
      {
        id: 17,
        asset: assets.sunflowerAndUltramarine,
        piecename: "Sunflower and Ultramarine",
        sold_out: false,
        price: 72000,
      },
      {
        id: 18,
        asset: assets.terracottaAndVerdant,
        piecename: "Terracotta & Verdant",
        sold_out: false,
        price: 72000,
      },
      {
        id: 19,
        asset: assets.vintageAndFancy,
        piecename: "Vintage and Fancy",
        sold_out: false,
        price: 72000,
      },
    ],
  },
  {
    id: 2,
    collection_name: "the cracks",
    no_of_pieces: 5,
    pieces: [
      {
        id: 1,
        asset: assets.theCracks1,
        piecename: "The Cracks 1",
        sold_out: false,
        price: 72000,
      },
      {
        id: 2,
        asset: assets.theCracks2,
        piecename: "The Cracks 2",
        sold_out: false,
        price: 72000,
      },
      {
        id: 3,
        asset: assets.theCracks3,
        piecename: "The Cracks 3",
        sold_out: false,
        price: 72000,
      },
      {
        id: 4,
        asset: assets.theCracks4,
        piecename: "The Cracks 4",
        sold_out: false,
        price: 72000,
      },
      {
        id: 5,
        asset: assets.theCracks5,
        piecename: "The Cracks 5",
        sold_out: false,
        price: 72000,
      },
    ],
  },
  {
    id: 3,
    collection_name: "faultlines",
    no_of_pieces: 2,
    pieces: [
      {
        id: 1,
        asset: assets.faultlines1,
        piecename: "Faultlines 1",
        sold_out: false,
        price: 72000,
      },
      {
        id: 2,
        asset: assets.faultlines2,
        piecename: "Faultlines 2",
        sold_out: false,
        price: 72000,
      },
    ],
  },
  {
    id: 4,
    collection_name: "fractal",
    no_of_pieces: 5,
    pieces: [
      {
        id: 1,
        asset: assets.fractal1,
        piecename: "Fractal 1",
        sold_out: false,
        price: 540000,
      },
      {
        id: 2,
        asset: assets.fractal2,
        piecename: "Fractal 2",
        sold_out: false,
        price: 540000,
      },
      {
        id: 3,
        asset: assets.fractal3,
        piecename: "Fractal 3",
        sold_out: false,
        price: 540000,
      },
      {
        id: 4,
        asset: assets.fractal4,
        piecename: "Fractal 4",
        sold_out: false,
        price: 540000,
      },
      {
        id: 5,
        asset: assets.fractal5,
        piecename: "Fractal 5",
        sold_out: false,
        price: 540000,
      },
    ],
  },
  {
    id: 5,
    collection_name: "interstellar",
    no_of_pieces: 5,
    pieces: [
      {
        id: 1,
        asset: assets.interstellar1,
        piecename: "Interstellar 1",
        sold_out: false,
        price: 540000,
      },
      {
        id: 2,
        asset: assets.interstellar2,
        piecename: "Interstellar 2",
        sold_out: false,
        price: 540000,
      },
      {
        id: 3,
        asset: assets.interstellar3,
        piecename: "Interstellar 3",
        sold_out: false,
        price: 540000,
      },
      {
        id: 4,
        asset: assets.interstellar4,
        piecename: "Interstellar 4",
        sold_out: false,
        price: 540000,
      },
      {
        id: 5,
        asset: assets.interstellar5,
        piecename: "Interstellar 5",
        sold_out: false,
        price: 540000,
      },
    ],
  },

  {
    id: 6,
    collection_name: "A collection of shadows (code)",
    no_of_pieces: 1,
    pieces: [
      {
        id: 1,
        asset: assets.faultlines,
        piecename: "Faultlines Shadow",
        sold_out: false,
        price: 72000,
      },
    ],
  },
  {
    id: 7,
    collection_name: "migration",
    no_of_pieces: 2,
    pieces: [
      {
        id: 1,
        asset: assets.migration1,
        piecename: "Migration 1",
        sold_out: false,
        price: 580000,
      },
      {
        id: 2,
        asset: assets.migration2,
        piecename: "Migration 2",
        sold_out: false,
        price: 580000,
      },
    ],
  },
  {
    id: 8,
    collection_name: "A collection of shadows (series)",
    no_of_pieces: 5,
    pieces: [
      {
        id: 1,
        asset: assets.azure,
        piecename: "Azure",
        sold_out: false,
        price: 1600000,
      },
      {
        id: 2,
        asset: assets.celestial,
        piecename: "Celestial",
        sold_out: false,
        price: 1600000,
      },
      {
        id: 3,
        asset: assets.chant,
        piecename: "Chant",
        sold_out: false,
        price: 1400000,
      },
      {
        id: 4,
        asset: assets.chant2,
        piecename: "Chant 2",
        sold_out: false,
        price: 1700000,
      },
      {
        id: 5,
        asset: assets.ethereal,
        piecename: "Ethereal",
        sold_out: false,
        price: 2155000,
      },
    ],
  },
  {
    id: 9,
    collection_name: "the funfun series",
    no_of_pieces: 5,
    pieces: [
      {
        id: 1,
        asset: assets.funfun1,
        piecename: "funfun 1",
        sold_out: false,
        price: 580000,
      },
      {
        id: 2,
        asset: assets.funfun2,
        piecename: "funfun 2",
        sold_out: false,
        price: 580000,
      },
      {
        id: 3,
        asset: assets.funfun3,
        piecename: "funfun 3",
        sold_out: false,
        price: 580000,
      },
      {
        id: 4,
        asset: assets.funfun4,
        piecename: "funfun 4",
        sold_out: false,
        price: 580000,
      },
      {
        id: 5,
        asset: assets.funfun5,
        piecename: "funfun 5",
        sold_out: false,
        price: 580000,
      },
    ],
  },
  {
    id: 10,
    collection_name: "M3t4m0rpho5i5",
    no_of_pieces: 4,
    pieces: [
      {
        id: 1,
        asset: assets.azureMetamorphosis,
        piecename: "Azure",
        sold_out: false,
        price: 730000,
      },
      {
        id: 2,
        asset: assets.crimson,
        piecename: "Crimson",
        sold_out: false,
        price: 730000,
      },
      {
        id: 3,
        asset: assets.gold,
        piecename: "Gold",
        sold_out: false,
        price: 730000,
      },
      {
        id: 4,
        asset: assets.lagoon,
        piecename: "Lagoon",
        sold_out: false,
        price: 730000,
      },
    ],
  },
  {
    id: 11,
    collection_name: "native soil",
    no_of_pieces: 4,
    pieces: [
      {
        id: 1,
        asset: assets.cosmos,
        piecename: "Cosmos",
        sold_out: false,
        price: 4000000,
      },
      {
        id: 2,
        asset: assets.crown,
        piecename: "Crown",
        sold_out: false,
        price: 4000000,
      },
      {
        id: 3,
        asset: assets.gathering,
        piecename: "Gathering",
        sold_out: false,
        price: 4000000,
      },
      {
        id: 4,
        asset: assets.sunlight,
        piecename: "Sunlight",
        sold_out: false,
        price: 4000000,
      },
    ],
  },
];
